[package]
name = "devto-bot-kick"
version = "0.1.0"
edition = "2021"

# [lib]
# crate-type = ["cdylib"]

[dependencies]
leptos = { version = "0.6.12", features = ["csr", "nightly"] }
wasm-bindgen = "0.2.92"

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "Window"
]
